
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app-container
          image: praveen1351/static-web-page:74ba81d400c7e8154f1f2ee826f9bf666f9b2e58
          ports:
            - containerPort: 80

