
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app-container
          image: praveen1351/static-web-page:19b74ff5d10abda84585f0dedd7ab12c9ef13dc8
          ports:
            - containerPort: 80

