
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app-container
          image: praveen1351/static-web-page:547502eacf7c7aaaa16b7ec93851da787fa5877c
          ports:
            - containerPort: 80

