
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app-container
          image: praveen1351/static-web-page:38cd2d8b7626a15646c7f2cd94840715abfbbcc9
          ports:
            - containerPort: 80

