
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app-container
          image: praveen1351/static-web-page:49d21d9ea411bec52daa4dde830d97b893e3ea5c
          ports:
            - containerPort: 80

